export type WorkspaceUserPreferences = {
  id: string;
  userId: string;
  workspaceId: string;
  defaultView: string;
  groupTasksBy: string;
  sortTasksBy: string;
  showCompletedTasks: boolean;
  showQuickAddButton: boolean;
  keyboardShortcutsEnabled: boolean;
  autoStartTimerOnTask: boolean;
  trackTime: boolean;
  trackBreaks: boolean;
  trackCompletionTimes: boolean;
  trackFocus: boolean;
  trackProjectSwitching: boolean;
  statsVisibility: string;
  showOnLeaderboard: boolean;
  shareAchievements: boolean;
  dataRetention: string;
  taskReminders: boolean;
  goalProgressNotifications: boolean;
  breakReminders: boolean;
  dailySummary: boolean;
  weeklySchedule: string | null;
  createdAt: string;
  updatedAt: string;
  deleted: boolean;
};
